[package]
name = "rust_chibicc"
version = "0.1.0"
authors = ["Atsushi KONISHI <atsushi524k10@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
